analysis:
  mode: advanced
  tenants: [a, b, c, d]
  metrics: all
  techniques: [correlation, pca, ica, clustering, anomaly_detection, signal_analysis]
  timeframe: all
  advanced_stats: true
  
data:
  path: demo-data/
  file_pattern: "*.csv"
  
processing:
  auto_format: true
  remove_outliers: true
  normalize: true
  anomaly_detection: true
  signal_filtering: true
  fourier_analysis: true
  
advanced:
  pca_components: auto
  correlation_methods: [pearson, spearman, kendall, mutual_info]
  clustering_methods: [kmeans, dbscan, hierarchical, gaussian_mixture]
  ica_components: auto
  anomaly_methods: [isolation_forest, local_outlier_factor, one_class_svm]
  signal_processing:
    fourier_transform: true
    wavelet_analysis: true
    autocorrelation: true
  ml_models:
    enable: true
    types: [regression, classification, time_series]
  
output:
  format: [png, svg, pdf, csv, json]
  directory: ./output/advanced_analysis
  save_data: true
  save_plots: true
  save_models: true
  save_intermediate: true
  
debug:
  verbose: true
  save_intermediate: true
  show_data_issues: true
  profile_performance: true
  memory_profiling: true
  
plots:
  basic_timeseries: true
  boxplots: true
  correlation_matrix: true
  tenant_comparison: true
  pca_plots: true
  clustering_plots: true
  anomaly_plots: true
  signal_analysis_plots: true
  fourier_plots: true
  ml_performance_plots: true
  interactive_plots: true
  dpi: 300
  figsize: [16, 12]
  
performance:
  parallel_processing: true
  max_workers: auto
  chunk_size: 1000
  memory_limit: 8GB
